# -*- coding: utf-8 -*-
#
# [自动生成的文件]
#
# 此文件由 Protobuf 编译器 (protoc) 根据 .proto 文件自动生成。
# 请勿直接手动修改此文件，所有更改都应在 .proto 源文件中进行，然后重新编译。
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Locale.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LocaleIds_pb2 as LocaleIds__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cLocale.proto\x12\"com.bapis.bilibili.metadata.locale\x1a\x0fLocaleIds.proto\"\xfa\x01\n\x06Locale\x12?\n\x08\x63_locale\x18\x01 \x01(\x0b\x32-.com.bapis.bilibili.metadata.locale.LocaleIds\x12?\n\x08s_locale\x18\x02 \x01(\x0b\x32-.com.bapis.bilibili.metadata.locale.LocaleIds\x12\x14\n\x08sim_code\x18\x03 \x01(\tB\x02\x18\x01\x12\x10\n\x08timezone\x18\x04 \x01(\t\x12\x12\n\nutc_offset\x18\x05 \x01(\t\x12\x18\n\x10is_daylight_time\x18\x06 \x01(\x08\x12\x18\n\x10\x61lways_translate\x18\x07 \x01(\x08\x42\rB\x0bLocaleProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Locale_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\013LocaleProto'
  _globals['_LOCALE'].fields_by_name['sim_code']._options = None
  _globals['_LOCALE'].fields_by_name['sim_code']._serialized_options = b'\030\001'
  _globals['_LOCALE']._serialized_start=70
  _globals['_LOCALE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
