# -*- coding: utf-8 -*-
#
# [自动生成的文件]
#
# 此文件由 Protobuf 编译器 (protoc) 根据 .proto 文件自动生成。
# 请勿直接手动修改此文件，所有更改都应在 .proto 源文件中进行，然后重新编译。
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocaleIds.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fLocaleIds.proto\x12\"com.bapis.bilibili.metadata.locale\"=\n\tLocaleIds\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0e\n\x06script\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\tB\x10\x42\x0eLocaleIdsProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LocaleIds_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\016LocaleIdsProto'
  _globals['_LOCALEIDS']._serialized_start=55
  _globals['_LOCALEIDS']._serialized_end=116
# @@protoc_insertion_point(module_scope)
