# -*- coding: utf-8 -*-
#
# [自动生成的文件]
#
# 此文件由 Protobuf 编译器 (protoc) 根据 .proto 文件自动生成。
# 请勿直接手动修改此文件，所有更改都应在 .proto 源文件中进行，然后重新编译。
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network_quality.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15network_quality.proto\x12\x1d\x63om.bilibili.lib.gtv.protocal\x1a\x0btypes.proto\"\x88\x01\n\nNetQuality\x12\x14\n\x0csuccess_rate\x18\x01 \x01(\x02\x12\r\n\x05speed\x18\x02 \x01(\x05\x12\x17\n\x0fspeed_timestamp\x18\x03 \x01(\x03\x12<\n\x08net_type\x18\x04 \x01(\x0e\x32*.com.bilibili.lib.gtv.protocal.NetworkType\"\xfe\x01\n\x07Network\x12\x38\n\x04type\x18\x01 \x01(\x0e\x32*.com.bilibili.lib.gtv.protocal.NetworkType\x12\x31\n\x02tf\x18\x02 \x01(\x0e\x32%.com.bilibili.lib.gtv.protocal.TFType\x12\x0b\n\x03oid\x18\x03 \x01(\t\x12=\n\x08\x63\x65llular\x18\x04 \x01(\x0e\x32+.com.bilibili.lib.gtv.protocal.CellularType\x12:\n\x07quality\x18\x05 \x01(\x0b\x32).com.bilibili.lib.gtv.protocal.NetQualityB!\n\x1d\x63om.bilibili.lib.gtv.protocalP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_quality_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.bilibili.lib.gtv.protocalP\001'
  _globals['_NETQUALITY']._serialized_start=70
  _globals['_NETQUALITY']._serialized_end=206
  _globals['_NETWORK']._serialized_start=209
  _globals['_NETWORK']._serialized_end=463
# @@protoc_insertion_point(module_scope)
