# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x1d\x63om.bilibili.lib.gtv.protocal*]\n\x06TFType\x12\x0e\n\nTF_UNKNOWN\x10\x00\x12\n\n\x06U_CARD\x10\x01\x12\t\n\x05U_PKG\x10\x02\x12\n\n\x06\x43_CARD\x10\x03\x12\t\n\x05\x43_PKG\x10\x04\x12\n\n\x06T_CARD\x10\x05\x12\t\n\x05T_PKG\x10\x06*^\n\x0bNetworkType\x12\x0e\n\nNT_UNKNOWN\x10\x00\x12\x08\n\x04WIFI\x10\x01\x12\x0c\n\x08\x43\x45LLULAR\x10\x02\x12\x0b\n\x07OFFLINE\x10\x03\x12\x0c\n\x08OTHERNET\x10\x04\x12\x0c\n\x08\x45THERNET\x10\x05*B\n\x0c\x43\x65llularType\x12\n\n\x06\x43_NONE\x10\x00\x12\x08\n\x04\x43_2G\x10\x01\x12\x08\n\x04\x43_3G\x10\x02\x12\x08\n\x04\x43_4G\x10\x03\x12\x08\n\x04\x43_5G\x10\x04\x42!\n\x1d\x63om.bilibili.lib.gtv.protocalP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.bilibili.lib.gtv.protocalP\001'
  _globals['_TFTYPE']._serialized_start=46
  _globals['_TFTYPE']._serialized_end=139
  _globals['_NETWORKTYPE']._serialized_start=141
  _globals['_NETWORKTYPE']._serialized_end=235
  _globals['_CELLULARTYPE']._serialized_start=237
  _globals['_CELLULARTYPE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
